version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    working_dir: /app
    command: npm run dev
